### ISSUE TITLE
ERROR: com.expressui.sample.SampleApplication - Terminal error:java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by marhipov** [juanosuna/expressui-framework#5]
1) start Jetty or Tomcat
2) http://localhost:8080/sample/app
3) set mouse cursor (click links) on the left table (contacts) , on the (for example) 3. row.
4) click right mouse button
5) see the context menu
6) click link mouse button on the 1st row ("view")
7) it comes error page:  ERROR: com.expressui.sample.SampleApplication - Terminal error:java.util.ConcurrentModificationException ...
///
This effect was on the 2 different PCs with windows7, DB was H2 and MySQL, Jetty and Tomcat. It happens in 100% situations.
///
@Juan:  It can be Vaadin problem:
a) https://vaadin.com/forum/-/message_boards/view_message/739951
b) https://vaadin.com/forum/-/message_boards/view_message/305492
///
I have compiled "old" version of ExpressUI/Sample  (rc1/juanosuna-expressui-framework-58bc631). I didn't see any problem here. 
@ Juan: coiuld you please think about, perhaps one can fix this in expressui code?

**Comment by marhipov** [comment]
Issue is resolved. The jdk version must be 7.

**Comment by juanosuna** [comment]
What JDK version resulted in the error?

If it is JDK 1.6, then I may re-open this issue to maintain compatibility.

**Comment by marhipov** [comment]
The java version was:
java version "1.6.0_32"
Java(TM) SE Runtime Environment (build 1.6.0_32-b05)
Java HotSpot(TM) 64-Bit Server VM (build 20.7-b02, mixed mode)

**Comment by juanosuna** [comment]
Fix will be in next minor release. ExpressUI should work fine with JDK1.6.

**Comment by marhipov** [comment]
OK, thank you,

I will test this tomorrow.

sincerely Michael Arkhypov

-------- Original-Nachricht --------
